"""Curated hospital formulary seed (~180 drugs) for demo CSV generation.

RxCUI values align with RxNorm prescribable concepts where available.
"""

from __future__ import annotations

# fmt: off
DEMO_FORMULARY_DRUGS: list[dict] = [
    # ── 抗凝 / 抗血小板 ─────────────────────────────────────────────
    {"cn": "华法林钠", "en": "warfarin", "trade": "华法林", "spec": "2.5mg", "form": "片剂", "route": "PO", "atc": "B01AA03", "rxcui": "11289", "high": 1, "alt": "enoxaparin"},
    {"cn": "华法林钠", "en": "warfarin", "trade": "华法林", "spec": "3mg", "form": "片剂", "route": "PO", "atc": "B01AA03", "rxcui": "11289", "high": 1, "alt": "enoxaparin"},
    {"cn": "依诺肝素", "en": "enoxaparin", "trade": "克赛", "spec": "0.4ml:4000IU", "form": "注射液", "route": "SC", "atc": "B01AB05", "rxcui": "67108", "high": 1},
    {"cn": "依诺肝素", "en": "enoxaparin", "trade": "克赛", "spec": "0.6ml:6000IU", "form": "注射液", "route": "SC", "atc": "B01AB05", "rxcui": "67108", "high": 1},
    {"cn": "肝素", "en": "heparin", "trade": "肝素钠", "spec": "12500IU", "form": "注射液", "route": "IV", "atc": "B01AB01", "rxcui": "5224", "high": 1, "alt": "enoxaparin"},
    {"cn": "阿司匹林", "en": "aspirin", "trade": "拜阿司匹林", "spec": "100mg", "form": "肠溶片", "route": "PO", "atc": "B01AC06", "rxcui": "1191"},
    {"cn": "阿司匹林", "en": "aspirin", "trade": "巴米尔", "spec": "0.5g", "form": "泡腾片", "route": "PO", "atc": "B01AC06", "rxcui": "1191"},
    {"cn": "氯吡格雷", "en": "clopidogrel", "trade": "波立维", "spec": "75mg", "form": "片剂", "route": "PO", "atc": "B01AC04", "rxcui": "32968", "alt": "aspirin"},
    {"cn": "替格瑞洛", "en": "ticagrelor", "trade": "倍林达", "spec": "90mg", "form": "片剂", "route": "PO", "atc": "B01AC24", "rxcui": "1116632", "high": 1},
    {"cn": "利伐沙班", "en": "rivaroxaban", "trade": "拜瑞妥", "spec": "20mg", "form": "片剂", "route": "PO", "atc": "B01AF01", "rxcui": "1114195", "high": 1, "formulary": 0, "alt": "warfarin"},
    {"cn": "达比加群", "en": "dabigatran", "trade": "泰毕全", "spec": "110mg", "form": "胶囊", "route": "PO", "atc": "B01AE07", "rxcui": "1037042", "high": 1, "dept": "心内科"},
    {"cn": "阿哌沙班", "en": "apixaban", "trade": "艾乐妥", "spec": "5mg", "form": "片剂", "route": "PO", "atc": "B01AF02", "rxcui": "1364430", "high": 1},
    # ── 解热镇痛 / NSAIDs ───────────────────────────────────────────
    {"cn": "布洛芬", "en": "ibuprofen", "trade": "芬必得", "spec": "0.3g", "form": "缓释胶囊", "route": "PO", "atc": "M01AE01", "rxcui": "5640", "alt": "acetaminophen"},
    {"cn": "布洛芬", "en": "ibuprofen", "trade": "美林", "spec": "0.1g/5ml", "form": "混悬液", "route": "PO", "atc": "M01AE01", "rxcui": "5640", "alt": "acetaminophen"},
    {"cn": "对乙酰氨基酚", "en": "acetaminophen", "trade": "泰诺林", "spec": "0.5g", "form": "片剂", "route": "PO", "atc": "N02BE01", "rxcui": "161"},
    {"cn": "对乙酰氨基酚", "en": "acetaminophen", "trade": "必理通", "spec": "0.65g", "form": "片剂", "route": "PO", "atc": "N02BE01", "rxcui": "161"},
    {"cn": "双氯芬酸", "en": "diclofenac", "trade": "扶他林", "spec": "50mg", "form": "肠溶片", "route": "PO", "atc": "M01AB05", "rxcui": "3355", "alt": "acetaminophen"},
    {"cn": "塞来昔布", "en": "celecoxib", "trade": "西乐葆", "spec": "0.2g", "form": "胶囊", "route": "PO", "atc": "M01AH01", "rxcui": "140587", "alt": "acetaminophen"},
    {"cn": "洛索洛芬", "en": "loxoprofen", "trade": "乐松", "spec": "60mg", "form": "片剂", "route": "PO", "atc": "M01AE03", "rxcui": "237884", "alt": "acetaminophen"},
    {"cn": "曲马多", "en": "tramadol", "trade": "奇曼丁", "spec": "50mg", "form": "胶囊", "route": "PO", "atc": "N02AX02", "rxcui": "10689", "narcotic": 2},
    {"cn": "吗啡", "en": "morphine", "trade": "美菲康", "spec": "10mg", "form": "注射液", "route": "IV", "atc": "N02AA01", "rxcui": "7052", "high": 1, "narcotic": 1},
    {"cn": "芬太尼", "en": "fentanyl", "trade": "芬太尼", "spec": "0.1mg/2ml", "form": "注射液", "route": "IV", "atc": "N01AH01", "rxcui": "4337", "high": 1, "narcotic": 1},
    # ── 抗生素 ─────────────────────────────────────────────────────
    {"cn": "阿莫西林", "en": "amoxicillin", "trade": "阿莫仙", "spec": "0.5g", "form": "胶囊", "route": "PO", "atc": "J01CA04", "rxcui": "723", "abx": 1, "alt": "azithromycin"},
    {"cn": "阿莫西林克拉维酸", "en": "amoxicillin clavulanate", "trade": "奥格门汀", "spec": "0.625g", "form": "片剂", "route": "PO", "atc": "J01CR02", "rxcui": "151392", "abx": 2},
    {"cn": "氨苄西林", "en": "ampicillin", "trade": "安必仙", "spec": "0.5g", "form": "胶囊", "route": "PO", "atc": "J01CA01", "rxcui": "733", "abx": 1, "alt": "amoxicillin"},
    {"cn": "青霉素", "en": "penicillin", "trade": "青霉素钠", "spec": "80万U", "form": "粉针", "route": "IV", "atc": "J01CE01", "rxcui": "7984", "abx": 1, "alt": "amoxicillin"},
    {"cn": "头孢氨苄", "en": "cephalexin", "trade": "先锋IV", "spec": "0.25g", "form": "胶囊", "route": "PO", "atc": "J01DB01", "rxcui": "2231", "abx": 1},
    {"cn": "头孢呋辛", "en": "cefuroxime", "trade": "西力欣", "spec": "0.75g", "form": "片剂", "route": "PO", "atc": "J01DC02", "rxcui": "2194", "abx": 2},
    {"cn": "头孢曲松", "en": "ceftriaxone", "trade": "罗氏芬", "spec": "1g", "form": "粉针", "route": "IV", "atc": "J01DD04", "rxcui": "2193", "abx": 3},
    {"cn": "头孢他啶", "en": "ceftazidime", "trade": "凯复定", "spec": "1g", "form": "粉针", "route": "IV", "atc": "J01DD02", "rxcui": "2191", "abx": 3},
    {"cn": "头孢哌酮舒巴坦", "en": "cefoperazone sulbactam", "trade": "舒普深", "spec": "1.5g", "form": "粉针", "route": "IV", "atc": "J01DD62", "rxcui": "236473", "abx": 3},
    {"cn": "哌拉西林他唑巴坦", "en": "piperacillin tazobactam", "trade": "特治星", "spec": "4.5g", "form": "粉针", "route": "IV", "atc": "J01CR05", "rxcui": "74169", "abx": 3},
    {"cn": "美罗培南", "en": "meropenem", "trade": "美平", "spec": "1g", "form": "粉针", "route": "IV", "atc": "J01DH02", "rxcui": "29561", "abx": 3, "dept": "ICU"},
    {"cn": "亚胺培南西司他丁", "en": "imipenem cilastatin", "trade": "泰能", "spec": "0.5g", "form": "粉针", "route": "IV", "atc": "J01DH51", "rxcui": "1659132", "abx": 3, "dept": "ICU"},
    {"cn": "万古霉素", "en": "vancomycin", "trade": "稳可信", "spec": "0.5g", "form": "粉针", "route": "IV", "atc": "J01XA01", "rxcui": "11124", "abx": 3, "high": 1},
    {"cn": "阿米卡星", "en": "amikacin", "trade": "丁胺卡那", "spec": "0.5g", "form": "注射液", "route": "IV", "atc": "J01GB06", "rxcui": "641", "abx": 3},
    {"cn": "庆大霉素", "en": "gentamicin", "trade": "庆大霉素", "spec": "80mg", "form": "注射液", "route": "IV", "atc": "J01GB03", "rxcui": "1428", "abx": 3},
    {"cn": "阿奇霉素", "en": "azithromycin", "trade": "希舒美", "spec": "0.25g", "form": "片剂", "route": "PO", "atc": "J01FA10", "rxcui": "18631", "abx": 2},
    {"cn": "克拉霉素", "en": "clarithromycin", "trade": "克拉仙", "spec": "0.25g", "form": "片剂", "route": "PO", "atc": "J01FA09", "rxcui": "21212", "abx": 2, "stock": 0, "alt": "azithromycin"},
    {"cn": "左氧氟沙星", "en": "levofloxacin", "trade": "可乐必妥", "spec": "0.5g", "form": "片剂", "route": "PO", "atc": "J01MA12", "rxcui": "82122", "abx": 3},
    {"cn": "莫西沙星", "en": "moxifloxacin", "trade": "拜复乐", "spec": "0.4g", "form": "片剂", "route": "PO", "atc": "J01MA14", "rxcui": "139896", "abx": 3},
    {"cn": "环丙沙星", "en": "ciprofloxacin", "trade": "悉复欢", "spec": "0.25g", "form": "片剂", "route": "PO", "atc": "J01MA02", "rxcui": "2551", "abx": 2},
    {"cn": "甲硝唑", "en": "metronidazole", "trade": "灭滴灵", "spec": "0.2g", "form": "片剂", "route": "PO", "atc": "J01XD01", "rxcui": "6922", "abx": 2},
    {"cn": "氟康唑", "en": "fluconazole", "trade": "大扶康", "spec": "0.15g", "form": "胶囊", "route": "PO", "atc": "J02AC01", "rxcui": "4450", "abx": 2},
    {"cn": "伏立康唑", "en": "voriconazole", "trade": "威凡", "spec": "0.2g", "form": "片剂", "route": "PO", "atc": "J02AC03", "rxcui": "280790", "abx": 3, "dept": "血液科"},
    # ── 降压 / 心衰 ─────────────────────────────────────────────────
    {"cn": "赖诺普利", "en": "lisinopril", "trade": "捷赐瑞", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "C09AA03", "rxcui": "29046", "alt": "amlodipine"},
    {"cn": "卡托普利", "en": "captopril", "trade": "开博通", "spec": "25mg", "form": "片剂", "route": "PO", "atc": "C09AA01", "rxcui": "1998", "alt": "losartan"},
    {"cn": "培哚普利", "en": "perindopril", "trade": "雅施达", "spec": "4mg", "form": "片剂", "route": "PO", "atc": "C09AA04", "rxcui": "54552", "alt": "amlodipine"},
    {"cn": "氯沙坦", "en": "losartan", "trade": "科素亚", "spec": "50mg", "form": "片剂", "route": "PO", "atc": "C09CA01", "rxcui": "52175", "alt": "amlodipine"},
    {"cn": "缬沙坦", "en": "valsartan", "trade": "代文", "spec": "80mg", "form": "胶囊", "route": "PO", "atc": "C09CA03", "rxcui": "69749", "alt": "amlodipine"},
    {"cn": "厄贝沙坦", "en": "irbesartan", "trade": "安博维", "spec": "0.15g", "form": "片剂", "route": "PO", "atc": "C09CA04", "rxcui": "83818", "alt": "amlodipine"},
    {"cn": "氨氯地平", "en": "amlodipine", "trade": "络活喜", "spec": "5mg", "form": "片剂", "route": "PO", "atc": "C08CA01", "rxcui": "17767"},
    {"cn": "硝苯地平", "en": "nifedipine", "trade": "拜新同", "spec": "30mg", "form": "控释片", "route": "PO", "atc": "C08CA05", "rxcui": "7417", "alt": "amlodipine"},
    {"cn": "非洛地平", "en": "felodipine", "trade": "波依定", "spec": "5mg", "form": "缓释片", "route": "PO", "atc": "C08CA02", "rxcui": "4316", "alt": "amlodipine"},
    {"cn": "美托洛尔", "en": "metoprolol", "trade": "倍他乐克", "spec": "25mg", "form": "片剂", "route": "PO", "atc": "C07AB02", "rxcui": "6918"},
    {"cn": "美托洛尔", "en": "metoprolol", "trade": "倍他乐克", "spec": "47.5mg", "form": "缓释片", "route": "PO", "atc": "C07AB02", "rxcui": "6918"},
    {"cn": "比索洛尔", "en": "bisoprolol", "trade": "康忻", "spec": "5mg", "form": "片剂", "route": "PO", "atc": "C07AB07", "rxcui": "19484"},
    {"cn": "卡维地洛", "en": "carvedilol", "trade": "络德", "spec": "12.5mg", "form": "片剂", "route": "PO", "atc": "C07AG02", "rxcui": "20352"},
    {"cn": "地高辛", "en": "digoxin", "trade": "地高辛", "spec": "0.25mg", "form": "片剂", "route": "PO", "atc": "C01AA05", "rxcui": "3407", "high": 1},
    {"cn": "胺碘酮", "en": "amiodarone", "trade": "可达龙", "spec": "0.2g", "form": "片剂", "route": "PO", "atc": "C01BD01", "rxcui": "703", "high": 1},
    {"cn": "呋塞米", "en": "furosemide", "trade": "速尿", "spec": "20mg", "form": "片剂", "route": "PO", "atc": "C03CA01", "rxcui": "4603"},
    {"cn": "呋塞米", "en": "furosemide", "trade": "速尿", "spec": "20mg/2ml", "form": "注射液", "route": "IV", "atc": "C03CA01", "rxcui": "4603"},
    {"cn": "托拉塞米", "en": "torsemide", "trade": "特苏尼", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "C03CA04", "rxcui": "38409"},
    {"cn": "螺内酯", "en": "spironolactone", "trade": "安体舒通", "spec": "20mg", "form": "片剂", "route": "PO", "atc": "C03DA01", "rxcui": "9997"},
    {"cn": "氢氯噻嗪", "en": "hydrochlorothiazide", "trade": "双氢克尿噻", "spec": "25mg", "form": "片剂", "route": "PO", "atc": "C03AA03", "rxcui": "5487"},
    {"cn": "硝酸甘油", "en": "nitroglycerin", "trade": "硝酸甘油", "spec": "0.5mg", "form": "舌下片", "route": "SL", "atc": "C01DA02", "rxcui": "4917", "high": 1},
    {"cn": "单硝酸异山梨酯", "en": "isosorbide mononitrate", "trade": "欣康", "spec": "20mg", "form": "片剂", "route": "PO", "atc": "C01DA14", "rxcui": "1364433"},
    # ── 调脂 ───────────────────────────────────────────────────────
    {"cn": "辛伐他汀", "en": "simvastatin", "trade": "舒降之", "spec": "20mg", "form": "片剂", "route": "PO", "atc": "C10AA01", "rxcui": "36567", "alt": "atorvastatin"},
    {"cn": "阿托伐他汀", "en": "atorvastatin", "trade": "立普妥", "spec": "20mg", "form": "片剂", "route": "PO", "atc": "C10AA05", "rxcui": "83367"},
    {"cn": "瑞舒伐他汀", "en": "rosuvastatin", "trade": "可定", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "C10AA07", "rxcui": "301542"},
    {"cn": "非诺贝特", "en": "fenofibrate", "trade": "力平之", "spec": "0.2g", "form": "胶囊", "route": "PO", "atc": "C10AB05", "rxcui": "8703"},
    # ── 降糖 ───────────────────────────────────────────────────────
    {"cn": "二甲双胍", "en": "metformin", "trade": "格华止", "spec": "0.5g", "form": "片剂", "route": "PO", "atc": "A10BA02", "rxcui": "6809"},
    {"cn": "二甲双胍", "en": "metformin", "trade": "格华止", "spec": "0.85g", "form": "片剂", "route": "PO", "atc": "A10BA02", "rxcui": "6809"},
    {"cn": "格列本脲", "en": "glibenclamide", "trade": "优降糖", "spec": "2.5mg", "form": "片剂", "route": "PO", "atc": "A10BB01", "rxcui": "4815", "alt": "metformin"},
    {"cn": "格列齐特", "en": "gliclazide", "trade": "达美康", "spec": "80mg", "form": "片剂", "route": "PO", "atc": "A10BB09", "rxcui": "4816", "alt": "metformin"},
    {"cn": "西格列汀", "en": "sitagliptin", "trade": "捷诺维", "spec": "100mg", "form": "片剂", "route": "PO", "atc": "A10BH01", "rxcui": "593411"},
    {"cn": "达格列净", "en": "dapagliflozin", "trade": "安达唐", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "A10BK01", "rxcui": "1373458"},
    {"cn": "利拉鲁肽", "en": "liraglutide", "trade": "诺和力", "spec": "18mg/3ml", "form": "注射液", "route": "SC", "atc": "A10BJ02", "rxcui": "897122", "high": 1},
    {"cn": "甘精胰岛素", "en": "insulin glargine", "trade": "来得时", "spec": "300U/3ml", "form": "注射液", "route": "SC", "atc": "A10AE04", "rxcui": "274783", "high": 1},
    {"cn": "门冬胰岛素", "en": "insulin aspart", "trade": "诺和锐", "spec": "300U/3ml", "form": "注射液", "route": "SC", "atc": "A10AB05", "rxcui": "51428", "high": 1},
    {"cn": "精蛋白锌胰岛素", "en": "insulin nph", "trade": "万苏林", "spec": "400U/10ml", "form": "注射液", "route": "SC", "atc": "A10AC01", "rxcui": "5856", "high": 1},
    # ── 消化 / PPI ──────────────────────────────────────────────────
    {"cn": "奥美拉唑", "en": "omeprazole", "trade": "洛赛克", "spec": "20mg", "form": "肠溶胶囊", "route": "PO", "atc": "A02BC01", "rxcui": "7646"},
    {"cn": "泮托拉唑", "en": "pantoprazole", "trade": "潘妥洛克", "spec": "40mg", "form": "肠溶片", "route": "PO", "atc": "A02BC02", "rxcui": "40790"},
    {"cn": "雷贝拉唑", "en": "rabeprazole", "trade": "瑞波特", "spec": "10mg", "form": "肠溶片", "route": "PO", "atc": "A02BC04", "rxcui": "114979"},
    {"cn": "埃索美拉唑", "en": "esomeprazole", "trade": "耐信", "spec": "40mg", "form": "肠溶片", "route": "PO", "atc": "A02BC05", "rxcui": "283742"},
    {"cn": "多潘立酮", "en": "domperidone", "trade": "吗丁啉", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "A03FA03", "rxcui": "3626"},
    {"cn": "甲氧氯普胺", "en": "metoclopramide", "trade": "胃复安", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "A03FA01", "rxcui": "6922"},
    {"cn": "昂丹司琼", "en": "ondansetron", "trade": "枢复宁", "spec": "8mg", "form": "片剂", "route": "PO", "atc": "A04AA01", "rxcui": "26225"},
    {"cn": "乳果糖", "en": "lactulose", "trade": "杜密克", "spec": "15ml", "form": "口服溶液", "route": "PO", "atc": "A06AD11", "rxcui": "6218"},
    # ── 呼吸 ───────────────────────────────────────────────────────
    {"cn": "沙丁胺醇", "en": "salbutamol", "trade": "万托林", "spec": "100μg", "form": "气雾剂", "route": "INH", "atc": "R03AC02", "rxcui": "435", "dept": "呼吸科"},
    {"cn": "布地奈德", "en": "budesonide", "trade": "普米克", "spec": "200μg", "form": "吸入剂", "route": "INH", "atc": "R03BA02", "rxcui": "19831"},
    {"cn": "氨茶碱", "en": "aminophylline", "trade": "氨茶碱", "spec": "0.25g", "form": "注射液", "route": "IV", "atc": "R03DA05", "rxcui": "689"},
    {"cn": "孟鲁司特", "en": "montelukast", "trade": "顺尔宁", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "R03DC03", "rxcui": "88249"},
    {"cn": "乙酰半胱氨酸", "en": "acetylcysteine", "trade": "沐舒坦", "spec": "0.3g", "form": "片剂", "route": "PO", "atc": "R05CB01", "rxcui": "197"},
    # ── 神经 / 精神 ─────────────────────────────────────────────────
    {"cn": "左甲状腺素钠", "en": "levothyroxine", "trade": "优甲乐", "spec": "50μg", "form": "片剂", "route": "PO", "atc": "H03AA01", "rxcui": "10582"},
    {"cn": "左甲状腺素钠", "en": "levothyroxine", "trade": "优甲乐", "spec": "100μg", "form": "片剂", "route": "PO", "atc": "H03AA01", "rxcui": "10582"},
    {"cn": "氟西汀", "en": "fluoxetine", "trade": "百忧解", "spec": "20mg", "form": "胶囊", "route": "PO", "atc": "N06AB03", "rxcui": "4493"},
    {"cn": "舍曲林", "en": "sertraline", "trade": "左洛复", "spec": "50mg", "form": "片剂", "route": "PO", "atc": "N06AB06", "rxcui": "36437"},
    {"cn": "艾司西酞普兰", "en": "escitalopram", "trade": "来士普", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "N06AB10", "rxcui": "321988"},
    {"cn": "文拉法辛", "en": "venlafaxine", "trade": "怡诺思", "spec": "75mg", "form": "缓释胶囊", "route": "PO", "atc": "N06AX16", "rxcui": "39786"},
    {"cn": "奥氮平", "en": "olanzapine", "trade": "再普乐", "spec": "5mg", "form": "片剂", "route": "PO", "atc": "N05AH03", "rxcui": "61381"},
    {"cn": "利培酮", "en": "risperidone", "trade": "维思通", "spec": "1mg", "form": "片剂", "route": "PO", "atc": "N05AX08", "rxcui": "35636"},
    {"cn": "喹硫平", "en": "quetiapine", "trade": "思瑞康", "spec": "0.1g", "form": "片剂", "route": "PO", "atc": "N05AH04", "rxcui": "51272"},
    {"cn": "地西泮", "en": "diazepam", "trade": "安定", "spec": "5mg", "form": "片剂", "route": "PO", "atc": "N05BA01", "rxcui": "3322", "narcotic": 2},
    {"cn": "劳拉西泮", "en": "lorazepam", "trade": "罗拉", "spec": "1mg", "form": "片剂", "route": "PO", "atc": "N05BA06", "rxcui": "6470", "narcotic": 2},
    {"cn": "佐匹克隆", "en": "zopiclone", "trade": "忆梦返", "spec": "7.5mg", "form": "片剂", "route": "PO", "atc": "N05CF01", "rxcui": "40048", "narcotic": 2},
    {"cn": "苯巴比妥", "en": "phenobarbital", "trade": "鲁米那", "spec": "30mg", "form": "片剂", "route": "PO", "atc": "N03AA02", "rxcui": "8134", "narcotic": 2},
    {"cn": "丙戊酸钠", "en": "valproic acid", "trade": "德巴金", "spec": "0.5g", "form": "缓释片", "route": "PO", "atc": "N03AG01", "rxcui": "11118", "high": 1},
    {"cn": "卡马西平", "en": "carbamazepine", "trade": "得理多", "spec": "0.2g", "form": "片剂", "route": "PO", "atc": "N03AF01", "rxcui": "2002", "high": 1},
    {"cn": "左乙拉西坦", "en": "levetiracetam", "trade": "开浦兰", "spec": "0.5g", "form": "片剂", "route": "PO", "atc": "N03AX14", "rxcui": "114477"},
    {"cn": "加巴喷丁", "en": "gabapentin", "trade": "Neurontin", "spec": "0.3g", "form": "胶囊", "route": "PO", "atc": "N03AX16", "rxcui": "25480"},
    # ── 过敏 / 抗组胺 ───────────────────────────────────────────────
    {"cn": "西替利嗪", "en": "cetirizine", "trade": "仙特明", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "R06AE07", "rxcui": "20610"},
    {"cn": "氯雷他定", "en": "loratadine", "trade": "开瑞坦", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "R06AX13", "rxcui": "28439"},
    {"cn": "异丙嗪", "en": "promethazine", "trade": "非那根", "spec": "25mg", "form": "片剂", "route": "PO", "atc": "R06AD02", "rxcui": "8745"},
    # ── 激素 / 免疫 ─────────────────────────────────────────────────
    {"cn": "泼尼松", "en": "prednisone", "trade": "强的松", "spec": "5mg", "form": "片剂", "route": "PO", "atc": "H02AB06", "rxcui": "8640"},
    {"cn": "甲泼尼龙", "en": "methylprednisolone", "trade": "美卓乐", "spec": "4mg", "form": "片剂", "route": "PO", "atc": "H02AB04", "rxcui": "6902"},
    {"cn": "地塞米松", "en": "dexamethasone", "trade": "地塞米松", "spec": "5mg", "form": "注射液", "route": "IV", "atc": "H02AB02", "rxcui": "3264"},
    {"cn": "环孢素", "en": "ciclosporin", "trade": "新山地明", "spec": "25mg", "form": "胶囊", "route": "PO", "atc": "L04AD01", "rxcui": "3008", "high": 1, "dept": "器官移植"},
    {"cn": "甲氨蝶呤", "en": "methotrexate", "trade": "甲氨蝶呤", "spec": "2.5mg", "form": "片剂", "route": "PO", "atc": "L04AX03", "rxcui": "6851", "high": 1},
    # ── 麻醉 / ICU ──────────────────────────────────────────────────
    {"cn": "丙泊酚", "en": "propofol", "trade": "丙泊酚", "spec": "0.2g/20ml", "form": "注射液", "route": "IV", "atc": "N01AX10", "rxcui": "8782", "high": 1, "dept": "麻醉科"},
    {"cn": "咪达唑仑", "en": "midazolam", "trade": "力月西", "spec": "5mg/1ml", "form": "注射液", "route": "IV", "atc": "N05CD08", "rxcui": "6960", "high": 1, "narcotic": 2, "dept": "麻醉科"},
    {"cn": "罗库溴铵", "en": "rocuronium", "trade": "爱可松", "spec": "50mg/5ml", "form": "注射液", "route": "IV", "atc": "M03AC09", "rxcui": "68139", "dept": "麻醉科"},
    {"cn": "去甲肾上腺素", "en": "norepinephrine", "trade": "去甲肾", "spec": "2mg/2ml", "form": "注射液", "route": "IV", "atc": "C01CA03", "rxcui": "7514", "high": 1, "dept": "ICU"},
    {"cn": "多巴胺", "en": "dopamine", "trade": "多巴胺", "spec": "20mg/2ml", "form": "注射液", "route": "IV", "atc": "C01CA04", "rxcui": "3628", "high": 1, "dept": "ICU"},
    {"cn": "肾上腺素", "en": "epinephrine", "trade": "肾上腺素", "spec": "1mg/1ml", "form": "注射液", "route": "IM", "atc": "C01CA24", "rxcui": "3992", "high": 1},
    # ── 维生素 / 电解质 / 其他常用药 ─────────────────────────────────
    {"cn": "维生素K1", "en": "vitamin k", "trade": "维生素K1", "spec": "10mg", "form": "注射液", "route": "IM", "atc": "B02BA01", "rxcui": "11246"},
    {"cn": "维生素B12", "en": "cyanocobalamin", "trade": "甲钴胺", "spec": "0.5mg", "form": "片剂", "route": "PO", "atc": "B03BA01", "rxcui": "11248"},
    {"cn": "叶酸", "en": "folic acid", "trade": "叶酸", "spec": "5mg", "form": "片剂", "route": "PO", "atc": "B03BB01", "rxcui": "4511"},
    {"cn": "氯化钾", "en": "potassium chloride", "trade": "氯化钾", "spec": "1g/10ml", "form": "注射液", "route": "IV", "atc": "B05XA01", "rxcui": "8591", "high": 1},
    {"cn": "葡萄糖酸钙", "en": "calcium gluconate", "trade": "葡萄糖酸钙", "spec": "1g/10ml", "form": "注射液", "route": "IV", "atc": "A12AA03", "rxcui": "1908"},
    {"cn": "碳酸氢钠", "en": "sodium bicarbonate", "trade": "小苏打", "spec": "0.5g/10ml", "form": "注射液", "route": "IV", "atc": "B05CB04", "rxcui": "36676"},
    {"cn": "辅酶Q10", "en": "coenzyme q10", "trade": "能气朗", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "C01EB09", "rxcui": "21406"},
    {"cn": "圣约翰草", "en": "st johns wort", "trade": "路优泰", "spec": "300mg", "form": "片剂", "route": "PO", "atc": "N06AX25", "rxcui": "258326"},
    {"cn": "银杏叶提取物", "en": "gingko", "trade": "金纳多", "spec": "40mg", "form": "片剂", "route": "PO", "atc": "N06DX02", "rxcui": "236778"},
    {"cn": "鱼油", "en": "fish oil", "trade": "深海鱼油", "spec": "1g", "form": "软胶囊", "route": "PO", "atc": "C10AX06", "rxcui": "4301"},
    # ── 肿瘤常用（住院） ─────────────────────────────────────────────
    {"cn": "奥沙利铂", "en": "oxaliplatin", "trade": "乐沙定", "spec": "50mg", "form": "粉针", "route": "IV", "atc": "L01XA03", "rxcui": "32592", "high": 1, "dept": "肿瘤科"},
    {"cn": "紫杉醇", "en": "paclitaxel", "trade": "泰素", "spec": "30mg", "form": "注射液", "route": "IV", "atc": "L01CD01", "rxcui": "56946", "high": 1, "dept": "肿瘤科"},
    {"cn": "顺铂", "en": "cisplatin", "trade": "顺铂", "spec": "30mg", "form": "注射液", "route": "IV", "atc": "L01XA01", "rxcui": "2555", "high": 1, "dept": "肿瘤科"},
    {"cn": "昂丹司琼", "en": "ondansetron", "trade": "欧贝", "spec": "8mg/4ml", "form": "注射液", "route": "IV", "atc": "A04AA01", "rxcui": "26225"},
    # ── 中成药（少量，演示目录多样性） ─────────────────────────────
    {"cn": "连花清瘟胶囊", "en": "lianhua qingwen", "trade": "连花清瘟", "spec": "0.35g*24", "form": "胶囊", "route": "PO", "atc": "Z01", "rxcui": "", "formulary": 1},
    {"cn": "参麦注射液", "en": "shenmai injection", "trade": "参麦", "spec": "10ml", "form": "注射液", "route": "IV", "atc": "Z02", "rxcui": "", "high": 1},
    {"cn": "丹参酮IIA磺酸钠", "en": "tanshinone iia", "trade": "丹参酮", "spec": "80mg/2ml", "form": "注射液", "route": "IV", "atc": "C01", "rxcui": ""},
    # ── 补充：专科 / 更多规格 ───────────────────────────────────────
    {"cn": "贝那普利", "en": "benazepril", "trade": "洛汀新", "spec": "10mg", "form": "片剂", "route": "PO", "atc": "C09AA07", "rxcui": "18867", "alt": "amlodipine"},
    {"cn": "替米沙坦", "en": "telmisartan", "trade": "美卡素", "spec": "40mg", "form": "片剂", "route": "PO", "atc": "C09CA07", "rxcui": "73494", "alt": "amlodipine"},
    {"cn": "吲达帕胺", "en": "indapamide", "trade": "寿比山", "spec": "2.5mg", "form": "片剂", "route": "PO", "atc": "C03BA11", "rxcui": "5764"},
    {"cn": "特拉唑嗪", "en": "terazosin", "trade": "高特灵", "spec": "2mg", "form": "片剂", "route": "PO", "atc": "C02CA01", "rxcui": "37798"},
    {"cn": "坦索罗辛", "en": "tamsulosin", "trade": "哈乐", "spec": "0.2mg", "form": "胶囊", "route": "PO", "atc": "G04CA02", "rxcui": "77492", "dept": "泌尿外科"},
    {"cn": "非那雄胺", "en": "finasteride", "trade": "保列治", "spec": "5mg", "form": "片剂", "route": "PO", "atc": "G04CB01", "rxcui": "25025", "dept": "泌尿外科"},
    {"cn": "索利那新", "en": "solifenacin", "trade": "卫喜康", "spec": "5mg", "form": "片剂", "route": "PO", "atc": "G04BD08", "rxcui": "358274"},
    {"cn": "托特罗定", "en": "tolterodine", "trade": "舍尼亭", "spec": "2mg", "form": "片剂", "route": "PO", "atc": "G04BD07", "rxcui": "119565"},
    {"cn": "别嘌醇", "en": "allopurinol", "trade": "别嘌醇", "spec": "0.1g", "form": "片剂", "route": "PO", "atc": "M04AA01", "rxcui": "519"},
    {"cn": "秋水仙碱", "en": "colchicine", "trade": "秋水仙碱", "spec": "0.5mg", "form": "片剂", "route": "PO", "atc": "M04AC01", "rxcui": "2683"},
    {"cn": "非布司他", "en": "febuxostat", "trade": "优立通", "spec": "40mg", "form": "片剂", "route": "PO", "atc": "M04AA03", "rxcui": "73689"},
    {"cn": "骨化三醇", "en": "calcitriol", "trade": "罗盖全", "spec": "0.25μg", "form": "胶囊", "route": "PO", "atc": "A11CC04", "rxcui": "1894"},
    {"cn": "阿法骨化醇", "en": "alfacalcidol", "trade": "阿法迪三", "spec": "0.25μg", "form": "胶囊", "route": "PO", "atc": "A11CC03", "rxcui": "1893"},
    {"cn": "左氧氟沙星", "en": "levofloxacin", "trade": "左氧氟沙星", "spec": "0.5g/100ml", "form": "注射液", "route": "IV", "atc": "J01MA12", "rxcui": "82122", "abx": 3},
    {"cn": "头孢唑林", "en": "cefazolin", "trade": "先锋V", "spec": "1g", "form": "粉针", "route": "IV", "atc": "J01DB04", "rxcui": "2180", "abx": 2},
    {"cn": "头孢克肟", "en": "cefixime", "trade": "世福素", "spec": "0.1g", "form": "胶囊", "route": "PO", "atc": "J01DD08", "rxcui": "2197", "abx": 2},
    {"cn": "多西环素", "en": "doxycycline", "trade": "强力霉素", "spec": "0.1g", "form": "胶囊", "route": "PO", "atc": "J01AA02", "rxcui": "3640", "abx": 2},
    {"cn": "米诺环素", "en": "minocycline", "trade": "美满霉素", "spec": "0.1g", "form": "胶囊", "route": "PO", "atc": "J01AA08", "rxcui": "6980", "abx": 2},
    {"cn": "更昔洛韦", "en": "ganciclovir", "trade": "赛美维", "spec": "0.25g", "form": "粉针", "route": "IV", "atc": "J05AB06", "rxcui": "4678", "abx": 3, "dept": "感染科"},
    {"cn": "阿昔洛韦", "en": "acyclovir", "trade": "阿昔洛韦", "spec": "0.2g", "form": "片剂", "route": "PO", "atc": "J05AB01", "rxcui": "281", "abx": 2},
    {"cn": "奥司他韦", "en": "oseltamivir", "trade": "达菲", "spec": "75mg", "form": "胶囊", "route": "PO", "atc": "J05AH02", "rxcui": "260101", "abx": 2, "stock": 0, "alt": "azithromycin"},
    {"cn": "利巴韦林", "en": "ribavirin", "trade": "病毒唑", "spec": "0.1g", "form": "片剂", "route": "PO", "atc": "J05AP01", "rxcui": "9344", "abx": 2},
    {"cn": "乳杆菌活菌", "en": "lactobacillus", "trade": "金双歧", "spec": "0.5g", "form": "片剂", "route": "PO", "atc": "A07FA01", "rxcui": ""},
    {"cn": "双歧杆菌", "en": "bifidobacterium", "trade": "培菲康", "spec": "0.21g", "form": "胶囊", "route": "PO", "atc": "A07FA01", "rxcui": ""},
    {"cn": "蒙脱石散", "en": "smectite", "trade": "思密达", "spec": "3g", "form": "散剂", "route": "PO", "atc": "A07BC05", "rxcui": ""},
    {"cn": "洛哌丁胺", "en": "loperamide", "trade": "易蒙停", "spec": "2mg", "form": "胶囊", "route": "PO", "atc": "A07DA03", "rxcui": "6468"},
    {"cn": "开塞露", "en": "glycerin enema", "trade": "开塞露", "spec": "20ml", "form": "灌肠剂", "route": "PR", "atc": "A06AG04", "rxcui": "4910"},
    {"cn": "聚乙二醇4000", "en": "macrogol", "trade": "福松", "spec": "10g", "form": "散剂", "route": "PO", "atc": "A06AD65", "rxcui": "236782"},
    {"cn": "铝碳酸镁", "en": "hydrotalcite", "trade": "达喜", "spec": "0.5g", "form": "咀嚼片", "route": "PO", "atc": "A02AX01", "rxcui": ""},
    {"cn": "硫糖铝", "en": "sucralfate", "trade": "硫糖铝", "spec": "0.25g", "form": "片剂", "route": "PO", "atc": "A02BX02", "rxcui": "10156"},
    {"cn": "瑞巴派特", "en": "rebamipide", "trade": "膜固思达", "spec": "0.1g", "form": "片剂", "route": "PO", "atc": "A02BX14", "rxcui": "236443"},
    {"cn": "熊去氧胆酸", "en": "ursodeoxycholic acid", "trade": "优思弗", "spec": "0.25g", "form": "胶囊", "route": "PO", "atc": "A05AA02", "rxcui": "11065"},
    {"cn": "多烯磷脂酰胆碱", "en": "polyene phosphatidylcholine", "trade": "易善复", "spec": "0.228g", "form": "胶囊", "route": "PO", "atc": "A05BA01", "rxcui": ""},
    {"cn": "还原型谷胱甘肽", "en": "glutathione", "trade": "阿拓莫兰", "spec": "0.6g", "form": "粉针", "route": "IV", "atc": "V03AB32", "rxcui": ""},
    {"cn": "异甘草酸镁", "en": "magnesium isoglycyrrhizinate", "trade": "异甘草酸镁", "spec": "50mg", "form": "注射液", "route": "IV", "atc": "A05BA05", "rxcui": ""},
    {"cn": "乙酰唑胺", "en": "acetazolamide", "trade": "乙酰唑胺", "spec": "0.25g", "form": "片剂", "route": "PO", "atc": "S01EC01", "rxcui": "167"},
    {"cn": "毛果芸香碱", "en": "pilocarpine", "trade": "匹鲁卡品", "spec": "1%", "form": "滴眼液", "route": "OPH", "atc": "S01EB01", "rxcui": "8327", "dept": "眼科"},
    {"cn": "噻吗洛尔", "en": "timolol", "trade": "噻吗洛尔", "spec": "0.5%", "form": "滴眼液", "route": "OPH", "atc": "S01ED01", "rxcui": "10600", "dept": "眼科"},
    {"cn": "左氧氟沙星", "en": "levofloxacin", "trade": "可乐必妥", "spec": "0.3%", "form": "滴眼液", "route": "OPH", "atc": "S01AE05", "rxcui": "82122", "abx": 2, "dept": "眼科"},
    {"cn": "布地奈德", "en": "budesonide", "trade": "雷诺考特", "spec": "64μg", "form": "鼻喷雾", "route": "NAS", "atc": "R01AD05", "rxcui": "19831"},
    {"cn": "糠酸莫米松", "en": "mometasone", "trade": "内舒拿", "spec": "50μg", "form": "鼻喷雾", "route": "NAS", "atc": "R01AD09", "rxcui": "108575"},
    {"cn": "氨溴索", "en": "ambroxol", "trade": "沐舒坦", "spec": "30mg", "form": "片剂", "route": "PO", "atc": "R05CB06", "rxcui": "623"},
    {"cn": "右美沙芬", "en": "dextromethorphan", "trade": "右美沙芬", "spec": "15mg", "form": "片剂", "route": "PO", "atc": "R05DA09", "rxcui": "3289"},
    {"cn": "氨酚羟考酮", "en": "oxycodone acetaminophen", "trade": "泰勒宁", "spec": "5mg/325mg", "form": "片剂", "route": "PO", "atc": "N02AJ17", "rxcui": "214182", "narcotic": 1, "high": 1},
    {"cn": "对乙酰氨基酚", "en": "acetaminophen", "trade": "泰诺", "spec": "0.5g/100ml", "form": "注射液", "route": "IV", "atc": "N02BE01", "rxcui": "161"},
    {"cn": "氟比洛芬酯", "en": "flurbiprofen axetil", "trade": "凯纷", "spec": "50mg/5ml", "form": "注射液", "route": "IV", "atc": "M01AE09", "rxcui": ""},
    {"cn": "帕瑞昔布", "en": "parecoxib", "trade": "特耐", "spec": "40mg", "form": "粉针", "route": "IV", "atc": "M01AH04", "rxcui": "279645"},
    {"cn": "卡介苗", "en": "bcg vaccine", "trade": "卡介苗", "spec": "0.1ml", "form": "注射液", "route": "ID", "atc": "J07AN01", "rxcui": ""},
    {"cn": "乙肝疫苗", "en": "hepatitis b vaccine", "trade": "乙肝疫苗", "spec": "20μg", "form": "注射液", "route": "IM", "atc": "J07BC01", "rxcui": ""},
    {"cn": "流感疫苗", "en": "influenza vaccine", "trade": "流感疫苗", "spec": "0.5ml", "form": "注射液", "route": "IM", "atc": "J07BB02", "rxcui": ""},
    {"cn": "人血白蛋白", "en": "albumin human", "trade": "人血白蛋白", "spec": "10g/50ml", "form": "注射液", "route": "IV", "atc": "B05AA01", "rxcui": "828529", "high": 1},
    {"cn": "免疫球蛋白", "en": "immune globulin", "trade": "静丙", "spec": "2.5g/50ml", "form": "注射液", "route": "IV", "atc": "J06BA02", "rxcui": "58230", "high": 1},
    {"cn": "肝素钠", "en": "heparin", "trade": "肝素钠", "spec": "12500U/2ml", "form": "封管液", "route": "IV", "atc": "B01AB01", "rxcui": "5224", "high": 1},
    {"cn": "低分子肝素", "en": "enoxaparin", "trade": "速碧林", "spec": "0.4ml:4100IU", "form": "注射液", "route": "SC", "atc": "B01AB05", "rxcui": "67108", "high": 1},
    {"cn": "氨甲环酸", "en": "tranexamic acid", "trade": "妥塞敏", "spec": "0.25g", "form": "片剂", "route": "PO", "atc": "B02AA02", "rxcui": "10691"},
    {"cn": "氨甲环酸", "en": "tranexamic acid", "trade": "妥塞敏", "spec": "0.25g/5ml", "form": "注射液", "route": "IV", "atc": "B02AA02", "rxcui": "10691", "high": 1},
    {"cn": "垂体后叶素", "en": "vasopressin", "trade": "垂体后叶素", "spec": "6U/1ml", "form": "注射液", "route": "IV", "atc": "H01BA01", "rxcui": "11149", "high": 1},
    {"cn": "缩宫素", "en": "oxytocin", "trade": "缩宫素", "spec": "10U/1ml", "form": "注射液", "route": "IV", "atc": "H01BB02", "rxcui": "7813", "high": 1, "dept": "产科"},
    {"cn": "米索前列醇", "en": "misoprostol", "trade": "喜占", "spec": "0.2mg", "form": "片剂", "route": "PO", "atc": "G02AD06", "rxcui": "6963", "dept": "产科"},
    {"cn": "黄体酮", "en": "progesterone", "trade": "黄体酮", "spec": "20mg", "form": "注射液", "route": "IM", "atc": "G03DA04", "rxcui": "8727", "dept": "产科"},
    {"cn": "戊酸雌二醇", "en": "estradiol valerate", "trade": "补佳乐", "spec": "1mg", "form": "片剂", "route": "PO", "atc": "G03CA03", "rxcui": "4124", "dept": "妇科"},
    {"cn": "炔雌醇环丙孕酮", "en": "ethinyl estradiol cyproterone", "trade": "达英-35", "spec": "复方", "form": "片剂", "route": "PO", "atc": "G03AA09", "rxcui": "214061", "dept": "妇科"},
    {"cn": "左炔诺孕酮", "en": "levonorgestrel", "trade": "毓婷", "spec": "0.75mg", "form": "片剂", "route": "PO", "atc": "G03AC03", "rxcui": "6373", "dept": "妇科"},
]
# fmt: on
